// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_dir/sample.proto

package tutorialpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4bf9506ce3192bfe, []int{0, 0}
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bf9506ce3192bfe, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=tutorial.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bf9506ce3192bfe, []int{0, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

// Our address book file is just one of these.
type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bf9506ce3192bfe, []int{1}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterEnum("tutorial.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Person)(nil), "tutorial.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "tutorial.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "tutorial.AddressBook")
}

func init() {
	proto.RegisterFile("proto_dir/sample.proto", fileDescriptor_4bf9506ce3192bfe)
}

var fileDescriptor_4bf9506ce3192bfe = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x8a, 0xd4, 0x40,
	0x10, 0x86, 0x4d, 0x36, 0x1b, 0x76, 0x2b, 0xb0, 0x84, 0xc6, 0x5d, 0x42, 0xdc, 0xc3, 0x90, 0x53,
	0x50, 0x4c, 0xe3, 0x28, 0x08, 0xde, 0x1c, 0x18, 0x50, 0x74, 0x9d, 0x35, 0x2a, 0xa2, 0x17, 0xed,
	0x24, 0xc5, 0xa4, 0x31, 0x49, 0x35, 0xdd, 0xc9, 0xe2, 0x5e, 0x7d, 0x05, 0x1f, 0xcd, 0x57, 0xf0,
	0x31, 0x3c, 0x48, 0x3a, 0x19, 0x5d, 0x96, 0xb9, 0xfd, 0xf5, 0xd7, 0x97, 0xbf, 0x2a, 0x5d, 0x70,
	0xa6, 0x34, 0xf5, 0xf4, 0xa5, 0x92, 0x9a, 0x1b, 0xd1, 0xaa, 0x06, 0x33, 0x6b, 0xb0, 0xa3, 0x7e,
	0xe8, 0x49, 0x4b, 0xd1, 0xc4, 0xe7, 0x5b, 0xa2, 0x6d, 0x83, 0x5c, 0x28, 0xc9, 0x45, 0xd7, 0x51,
	0x2f, 0x7a, 0x49, 0x9d, 0x99, 0xb8, 0xe4, 0x8f, 0x03, 0xfe, 0x25, 0x6a, 0x43, 0x1d, 0x63, 0xe0,
	0x75, 0xa2, 0xc5, 0xc8, 0x59, 0x38, 0xe9, 0x71, 0x6e, 0x35, 0x3b, 0x01, 0x57, 0x56, 0x91, 0xbb,
	0x70, 0xd2, 0xc3, 0xdc, 0x95, 0x15, 0xbb, 0x0b, 0x87, 0xd8, 0x0a, 0xd9, 0x44, 0x07, 0x16, 0x9a,
	0x0a, 0xf6, 0x04, 0x7c, 0x55, 0x53, 0x87, 0x26, 0xf2, 0x16, 0x07, 0x69, 0xb0, 0x3c, 0xcf, 0x76,
	0xd3, 0xb3, 0x29, 0x3b, 0xbb, 0x1c, 0xdb, 0x6f, 0x86, 0xb6, 0x40, 0x9d, 0xcf, 0x6c, 0xfc, 0x01,
	0x82, 0x1b, 0x36, 0x3b, 0x03, 0xbf, 0xb3, 0x6a, 0x5e, 0x60, 0xae, 0x58, 0x06, 0x5e, 0x7f, 0xad,
	0xd0, 0x2e, 0x71, 0xb2, 0x8c, 0xf7, 0x47, 0xbf, 0xbf, 0x56, 0x98, 0x5b, 0x2e, 0x79, 0x00, 0xc7,
	0xff, 0x2c, 0x06, 0xe0, 0x5f, 0x6c, 0x56, 0x2f, 0x5f, 0xaf, 0xc3, 0x3b, 0xec, 0x08, 0xbc, 0x17,
	0x9b, 0x8b, 0x75, 0xe8, 0x8c, 0xea, 0xe3, 0x26, 0x7f, 0x15, 0xba, 0xc9, 0x53, 0x08, 0x9e, 0x57,
	0x95, 0x46, 0x63, 0x56, 0x44, 0xdf, 0x58, 0x0a, 0xbe, 0x42, 0x52, 0xcd, 0xf8, 0x08, 0xe3, 0x8f,
	0x84, 0xb7, 0xa7, 0xe5, 0x73, 0x7f, 0xf9, 0x15, 0x82, 0x4f, 0x34, 0xe8, 0x77, 0xa8, 0xaf, 0x64,
	0x89, 0xec, 0x2d, 0x78, 0xeb, 0xb2, 0x26, 0x76, 0xfa, 0xff, 0x83, 0x1b, 0xb9, 0xf1, 0x7e, 0x3b,
	0xb9, 0xf7, 0xe3, 0xd7, 0xef, 0x9f, 0xee, 0x69, 0x12, 0xf2, 0xab, 0x47, 0x1c, 0xbf, 0xdb, 0xfb,
	0x71, 0x2c, 0x6b, 0x7a, 0xe6, 0xdc, 0x5f, 0xf1, 0xcf, 0x0f, 0xb7, 0xb2, 0xaf, 0x87, 0x22, 0x2b,
	0xa9, 0xe5, 0xd3, 0x99, 0x35, 0x1a, 0x14, 0xba, 0xac, 0x77, 0xb0, 0xe1, 0xbb, 0x5c, 0x55, 0x14,
	0xbe, 0x65, 0x1e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x36, 0x25, 0x5d, 0x13, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// YourServiceClient is the client API for YourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YourServiceClient interface {
	Echo(ctx context.Context, in *AddressBook, opts ...grpc.CallOption) (*AddressBook, error)
}

type yourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYourServiceClient(cc grpc.ClientConnInterface) YourServiceClient {
	return &yourServiceClient{cc}
}

func (c *yourServiceClient) Echo(ctx context.Context, in *AddressBook, opts ...grpc.CallOption) (*AddressBook, error) {
	out := new(AddressBook)
	err := c.cc.Invoke(ctx, "/tutorial.YourService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YourServiceServer is the server API for YourService service.
type YourServiceServer interface {
	Echo(context.Context, *AddressBook) (*AddressBook, error)
}

// UnimplementedYourServiceServer can be embedded to have forward compatible implementations.
type UnimplementedYourServiceServer struct {
}

func (*UnimplementedYourServiceServer) Echo(ctx context.Context, req *AddressBook) (*AddressBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}

func RegisterYourServiceServer(s *grpc.Server, srv YourServiceServer) {
	s.RegisterService(&_YourService_serviceDesc, srv)
}

func _YourService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YourServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.YourService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YourServiceServer).Echo(ctx, req.(*AddressBook))
	}
	return interceptor(ctx, in, info, handler)
}

var _YourService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.YourService",
	HandlerType: (*YourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _YourService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto_dir/sample.proto",
}
